name: TORUS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run validation tests
      run: |
        cd toroidal_diffusion_complete_website/toroidal_diffusion_project
        python test_validation.py
    
    - name: Run quick test
      run: |
        cd toroidal_diffusion_complete_website/toroidal_diffusion_project
        python quick_test.py
    
    - name: Run benchmark
      run: |
        cd toroidal_diffusion_complete_website/toroidal_diffusion_project
        python benchmark.py --device cpu --batch-size 2 --steps 5 --model torus
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: benchmark-results-${{ matrix.python-version }}
        path: toroidal_diffusion_complete_website/toroidal_diffusion_project/benchmarks/ 